### ISSUE TITLE
Compatibility: Rendering of visual elements fails when utilizing canvas

### ISSUE THREAD

**Issue by firestar9114** [WeNeedCoffee/Fabritone#3]
Rendering of visual elements, such as path prediction, fails when utilizing canvas.  This makes the use of shaders, certain resource packs, lighting engines, etc impossible to use with Fabritone if those path guides are desired.  Please consider making the rendering of fabritone visual elements compatible with canvas.  https://www.curseforge.com/minecraft/mc-mods/canvas-renderer

**Comment by Dalethium** [comment]
This project is a personal port that I worked on many months back for various reasons, you can find the official one with more recent updates here: https://gitlab.com/CDAGaming/fabritone
