### ISSUE TITLE
Improvement: Integration with Xaero's world map and minimap

### ISSUE THREAD

**Issue by firestar9114** [WeNeedCoffee/Fabritone#4]
Integrate the fabritone waypoint system with the Xaero's waypoints.

Forum links to Xaero's world map and minimap:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2379024-xaeros-minimap-1-16-5-forge-fabric-1-15-2-1-14-4-1
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2624027-xaeros-world-map-1-16-5-forge-fabric-1-15-2-1-14-4

**Comment by Dalethium** [comment]
This project is a personal port that I worked on many months back for various reasons, you can find the official one with more recent updates here: https://gitlab.com/CDAGaming/fabritone
