### ISSUE TITLE
Should this project be archived / is it obsolete?

### ISSUE THREAD

**Issue by James-E-A** [WeNeedCoffee/Fabritone#6]
I see this project hasn't been updated in a while.

Would you consider [archiving it](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository) and putting a link to the current port in the README?

https://gitlab.com/CDAGaming/fabritone/-/pipelines

**Comment by ikeafridge4** [comment]
bruh i hope they dont archive this

**Comment by Dalethium** [comment]
The author is correct, I've noticed a bit of activity on this repo and should have clarified this. I'll now be archiving this repo, you can go here for the current one: https://gitlab.com/CDAGaming/fabritone/-/pipelines
